# -*- coding: utf-8 -*-
"""Retail.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i2yybLm45E3NchT-skIeoC2mYZssoSqs
"""

import pandas as pd
import numpy as np
ab=pd.read_csv("retails.csv")
ab.tail()

ab.columns

ab.info()

#cheking for null values and drop them if exist
ab.isnull().sum()
ab=ab.dropna()

#check for an duplicated values
ab.duplicated().sum()

#statistical summary for numeric data
ab.describe()

#statstical summary for categorical columns
ab.describe(include=object)

#convert order date an dship date column to datetime
ab["Order Date"]=pd.to_datetime(ab['Order Date'])
ab["Ship Date"]=pd.to_datetime(ab["Ship Date"])

ab["Order Date"].info()
ab["Ship Date"].info()

num_col=[]
for column in ab.columns:
  if ab[column].dtype=="float64" or ab[column].dtype=="int64":
    num_col.append(column)
print(num_col)

for column in num_col:
     ab[column]=(ab[column].astype(str).replace(",","",regex=False).astype(float))

ab.info()

ab["Order Quantity"]=ab["Order Quantity"].astype("Int64")

ab["Order Quantity"].isnull().sum()

for column in ab.columns:
  if ab[column].dtype==object:
    ab[column]=ab[column].str.replace("%","",regex=False)

ab









